apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spr-test-gh-quay-tekton-development
  namespace: rhtap-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/spr-test-gh-quay-tekton/overlays/development
    repoURL: https://github.com/RHTAP-RHDH/sprgh-qy-tekton-16apr-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
