apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: spr-test-gh-quay-tekton 
  janus-idp.io/tekton: spr-test-gh-quay-tekton
  backstage.io/kubernetes-id: spr-test-gh-quay-tekton
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: spr-test-gh-quay-tekton
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml